application: survey-monk
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images
- url: /javascripts
  static_dir: javascripts
- url: /jquery
  static_dir: jquery
- url: /.*
  script: survey.py